apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-cwyl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-cwyl@sha256:36ac622890d1b321705c99b39adf1abcda52f74d031eaeff260b52385acbc4c7
        name: my-nodejs
        resources: {}
status: {}
