apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-5ppf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-5ppf@sha256:aa4fc2c839284ddbb2f408f76612f32ef4b3a85b1c42854150ff368e44925f95
        name: my-python
        resources: {}
status: {}
